title: Engineering Platforms for the Agentic AI Era
description: Cloud, Data, Observability & Agentic AI insights from 20+ years of enterprise platform leadership
baseurl: ""   # important for project sites!
url: "https://dhineshkumarganesan.github.io"
theme: minima

exclude:
  - README.md

comments:
  provider: giscus
  giscus:
    repo: dhineshkumarganesan/dhineshkumarganesan.github.io
    repo_id: # get from giscus.app
    category: Announcements
    category_id: # get from giscus.app

google-site-verification=Qno89N3kMEtY-AHAno0NpKDthMCPbnjRd3cNNwrBtaA
